module.exports = {
	ADMIN_MODEL: 'admin',
	ROLE_MODEL: 'role',
	GENDER_MODEL: 'gender',
	KEY_TOKEN_MODEL: 'keyToken',
	SPECIALTY_MODEL: 'specialty',
	POSITION_MODEL: 'position',
	WORKING_HOUR_MODEL: 'workingHour',
	DOCTOR_MODEL: 'doctor',
	PATIENT_MODEL: 'patient',
	BOOKING_MODEL: 'booking',
	BLOG_CATEGORY_MODEL: 'blogCategory',
	BLOG_MODEL: 'blog',
	HTML_CONTENT_MODEL: 'htmlContent',
	LINK_MODEL: 'link',
};
